server:
  port: 8084

spring:
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
    static-path-pattern: /static/**
    #???????
    servlet:
      path: /uin

  datasource:
    password: 12345678
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=UTF-8&serverTimezone
    =Asia/Shanghai
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
